spring.application.name=core-identity-service
spring.profiles.active=@activatedProperties@
#security
spring.cloud.config.uri=${CONFIG_SERVER_URI:@configServerUrl@}
spring.security.user.name=${CONFIG_SERVER_USER}
spring.security.user.password=${CONFIG_SERVER_PASSWORD}



